site_name: My notes # 左上角标题
site_url: null
site_description: null
site_author: author
# repo_name: 'GitHub'
# repo_url: https://github.com/Skyer19/notes
# edit_uri
docs_dir: 'docs'
copyright: "Copyright &copy; 2024"

theme:
  name: 'material'
  # logo:
    # icon: 'cloud'
  # favicon: 'assets/images/favicon.ico'
  language: 'en'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - content.code.select


# Customization
extra:

  search:
    language: 'en'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - admonition                                      # 注解块支持
  - pymdownx.arithmatex                             # 数学公式的TeX语法支持
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:                                 # 表情支持
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  # - pymdownx.superfences
  - pymdownx.tasklist:                              # 任务清单支持
      custom_checkbox: true
  - pymdownx.tilde
  - meta # 元数据支持
  # 图片                                         
  - attr_list
  - md_in_html



nav:
    - Home: 'index.md'
    - Courses:
      - Principle of Distributed Ledgers:
        - 'Lecture 1': ./courses/pdl/l1.md
        - 'Lecture 2': ./courses/pdl/l2.md
      - Natural language processing:
        - 'Lecture 1': ./courses/nlp/l1.md
        - 'Lecture 2': ./courses/nlp/l2.md
    - Python:
        - 'Python常用指令': ./Python/Python常用指令.md
        - 'wandb使用': ./Python/wandb使用.md
    - Linux:
        - '终端命令': ./Linux/终端命令.md
        - '文件(目录)操作': ./Linux/文件(目录)操作.md
        - 'screen命令': ./Linux/screen命令.md
        - 'tmux命令': ./Linux/tmux命令.md
        - 'pip使用': ./Linux/pip使用.md
        - 'conda使用': ./Linux/conda使用.md
    - Project:
        - '生物信息学领域的任务': ./Project/生物信息学领域的任务.md
        - 'H5AD文件': ./Project/H5AD文件格式.md
        - 基因调控网络:
          - '基因调控网络': ./Project/GRN.md
          - 'Transformer GRN Inference': ./Project/transformer_GRN_Inference.md    
        - scGPT: 
          - 'scGPT pipline': ./Project/scGPT/scGPT_pipline.md
   #       - 'scGPT 结构': ./Project/scGPT/scGPT_structure.md       
         
    - Finance:
        - '基本金融知识': ./Finance/1-基本金融知识.md
        - '金融工具': ./Finance/2-金融工具.md
        - '金融机构': ./Finance/4-金融机构.md
        - '金融分析': ./Finance/3-金融分析.md  
    - Quant:
        - '量化工作介绍': ./Quant/量化工作介绍.md
        - '量化技能': ./Quant/量化技能.md

    - French:
        - 'French 1': ./French/1.md

    # - About: 'about.md'





