site_name: My notes # 左上角标题
site_url: null
site_description: null
site_author: author
# repo_name: 'GitHub'
# repo_url: https://github.com/Skyer19/notes
# edit_uri
docs_dir: 'docs'
copyright: "Copyright &copy; 2024"

theme:
  name: 'material'
  # logo:
    # icon: 'cloud'
  # favicon: 'assets/images/favicon.ico'
  language: 'en'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - content.code.select
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode


# Customization
extra:

  search:
    language: 'en'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - admonition                                      # 注解块支持
  - pymdownx.arithmatex                             # 数学公式的TeX语法支持
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:                                 # 表情支持
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  # - pymdownx.superfences
  - pymdownx.tasklist:                              # 任务清单支持
      custom_checkbox: true
  - pymdownx.tilde
  - meta # 元数据支持
  # 图片                                         
  - attr_list
  - md_in_html



nav:
    - Home: 'index.md'
    # - Courses:
    #   - Principle of Distributed Ledgers:
    #     - 'Lecture 1': ./Courses/pdl/l1.md
    #     - 'Lecture 2': ./Courses/pdl/l2.md
    #   - Natural language processing:
    #     - 'Word2Vec': ./Courses/nlp/Word2Vec.md

    #     - Pre-training models:
    #       - Encoder model:
    #         - 'BERT': ./Courses/nlp/Pre-training_models/encoder/BERT.md
    #       - Decoder model:
    #         - 'Method': ./Courses/nlp/Pre-training_models/decoder/Learning_methods.md
    #       - Encoder-Decoder model:
    #         - 'Method': ./Courses/nlp/Pre-training_models/encoder-decoder/method.md
    #     - 'Transformer': ./Courses/nlp/transformer.md
    #     - 'Evaluating LLM': ./Courses/nlp/EvaluatingLLM.md
    - Python:
        - 'Python常用指令': ./Python/Python常用指令.md
        - 'wandb使用': ./Python/wandb使用.md
        - 'DataFrame': ./Python/dataFrame使用.md
    - Linux:
        - '终端命令': ./Linux/终端命令.md
        - '文件(目录)操作': ./Linux/文件(目录)操作.md
        - 'screen命令': ./Linux/screen命令.md
        - 'tmux命令': ./Linux/tmux命令.md
        - 'pip使用': ./Linux/pip使用.md
        - 'conda使用': ./Linux/conda使用.md
        - 'Jupyter Notebook': ./Linux/Jupyter_Notebook.md

    - Project:
        - 1.基础知识: 
          - '名词解释': ./Project/基础知识/名词解释.md
          - '基因表达数据': ./Project/基础知识/基因表达数据.md
          - '生物信息学领域的任务': ./Project/基础知识/生物信息学领域的任务.md
          - 'H5AD文件': ./Project/基础知识/H5AD文件格式.md

        - 2.基因调控网络:
          - 'GRN': ./Project/GRN/GRN.md
          - 'GRN Code': ./Project/GRN/GRN_code.md  
          - 'GRN Inference - Transformer': ./Project/GRN/transformer_GRN_Inference.md 
        - 3.相关方法和模型:   
          - 'Transformer': ./Courses/nlp/transformer.md
          - 'Gene2Vec': ./Project/相关方法和模型/Gene2Vec.md
          - 'scBERT': ./Project/相关方法和模型/scBERT.md
          - 'Flash-Attention Blocks': ./Project/相关方法和模型/Flash-Attention_Blocks.md          
        - 4.scGPT: 
          - 'scGPT': ./Project/scGPT/scGPT.md
          - '单细胞多组学': ./Project/scGPT/单细胞多组学.md
          - '单细胞RNA测序': ./Project/scGPT/单细胞RNA测序.md
          - '根据细胞或基因表达提示生成细胞的基因表达水平': ./Project/scGPT/根据细胞或基因表达提示生成细胞的基因表达水平.md
          - '生成式预训练模型': ./Project/scGPT/生成式预训练模型.md

          # - 'Pipeline': ./Project/scGPT/scGPT_pipeline.md
          - scGPT code Package:
            - Modules:
                - 'scgpt.model package': ./Project/scGPT/code/Modules/scGPT_code_scgpt.model_package.md
                - 'scgpt.scbank package': ./Project/scGPT/code/Modules/scGPT_code_scgpt.scbank_package.md           
                - 'scgpt.tasks package': ./Project/scGPT/code/Modules/scGPT_code_scgpt.tasks_package.md
                - 'scgpt.tokenizer package': ./Project/scGPT/code/Modules/scGPT_code_scgpt.tokenizer_package.md               
                - 'scgpt.utils package': ./Project/scGPT/code/Modules/scGPT_code_scgpt.utils_package.md 
            - 'scgpt.data_collator': ./Project/scGPT/code/scgpt.data_collator.md   
            - 'scgpt.data_sampler': ./Project/scGPT/code/scgpt.data_sampler.md   
            - 'scgpt.loss': ./Project/scGPT/code/scgpt.loss.md   
            - 'scgpt.preprocess': ./Project/scGPT/code/scgpt.preprocess.md
            - 'scgpt.trainer': ./Project/scGPT/code/scgpt.trainer.md
        - 'paperReading': ./Project/paperReading.md
    - Finance:
        - '基本金融知识': ./Finance/1-基本金融知识.md
        - '金融工具': ./Finance/2-金融工具.md
        - '金融机构': ./Finance/4-金融机构.md
        - '金融分析': ./Finance/3-金融分析.md  
    - Quant:
        - '量化工作介绍': ./Quant/量化工作介绍.md
        - '量化技能': ./Quant/量化技能.md

    # - French:
    #     - 'French 1': ./French/1.md
    #     - 'French 1': ./French/2.md
    - 机器学习:
        - 基础知识:
          - '分类和回归': ./MachineLeanring/基础知识/分类和回归.md
          - 'Lazy vs Eager learning': ./MachineLeanring/基础知识/LazyEagerLearning.md
          - 'Normalisation': ./MachineLeanring/基础知识/Normalisation.md
          - 'Bias-variance': ./MachineLeanring/基础知识/Bias-variance.md
          - '评估指标': ./MachineLeanring/基础知识/评估指标.md
        - Supervised Learning:
          - 'KNN': ./MachineLeanring/SL/KNN.md
          - 'Decision Tree': ./MachineLeanring/SL/DecisionTrees.md
        - Unsupervised Learning:
          - Clustering:
            - 概念: 'about.md'
            - K-means: 'about.md'
          - Probability Density Estimation:
            - 概念: 'about.md'
            - Non-parametric approaches: 'about.md'
            - Parametric approaches: 'about.md'
            - GMM-EM: 'about.md'
    - 自然语言处理:
        - 语言模型的发展:
          - '统计语言模型': ./nlp/统计语言模型.md
          - 'NNLM模型': ./nlp/NNLM模型.md
          - 'Word2Vec模型': ./nlp/Word2Vec模型.md
          - 'ELMo模型': ./nlp/ELMo模型.md
          - 'BERT': ./nlp/BERT模型.md
          - 'Transformer': ./nlp/Transformer模型.md

        # - Pre-training models:
        #   - Encoder model:
        #     - 'BERT': ./Courses/nlp/Pre-training_models/encoder/BERT.md
        #   - Decoder model:
        #     - 'Method': ./Courses/nlp/Pre-training_models/decoder/Learning_methods.md
        #   - Encoder-Decoder model:
        #     - 'Method': ./Courses/nlp/Pre-training_models/encoder-decoder/method.md
        # - 'Transformer': ./Courses/nlp/transformer.md
   
        - '大模型的评估方法': ./Courses/nlp/EvaluatingLLM.md
    
    # - About: 'about.md'





